######################################################################
#
# File name : test_simulate.do
# Created on: Thu Oct 01 11:15:02 CEST 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_3_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {test_wave.do}

view wave
view structure
view signals

do {test.udo}

run 1000ns
